### ISSUE TITLE
Regression: hotplate driver does not initialize asyncio.lock

### ISSUE THREAD

**Issue by alexrudd2** [numat/ika#23]
```
  File "/Users/a.ruddick/Documents/github/ika/ika/driver.py", line 33, in query
    if not self.lock:
           ^^^^^^^^^
AttributeError: 'Hotplate' object has no attribute 'lock'
```

Most likely introduced in https://github.com/numat/ika/commit/a2c673ab70c47d27c934ebef3e00e4710422e781, because the overridden constructor does not initialize `self.lock`

**Comment by alexrudd2** [comment]
This wasn't caught in the test suite, since it didn't use `self.lock`.  https://github.com/numat/ika/commit/5c65b7210e38deb1754ad99f0c50ddd55c67c3e7 improves the mock to catch future regressions.

![image](https://github.com/numat/ika/assets/52292902/dcd36f06-55c0-4176-a358-418631148ee2)
